import os
import time as s

def clearConsole():
    command = 'clear'
    if os.name in ('nt', 'dos'):  # If Machine is running on Windows, use cls
        command = 'cls'
    os.system(command)

def printPokerHouse():
  print("----- Welcome To Louis' Poker House -----" )
  s.sleep(0)
  clearConsole()
  print("- ---- Welcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("-- --- Welcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("--- -- Welcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("---- - Welcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("-----  Welcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- W elcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- We lcome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Wel come To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welc ome To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welco me To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcom e To Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome T o Louis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To L ouis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Lo uis' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Lou is' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Loui s' Poker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' P oker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Po ker House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Pok er House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poke r House -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker H ouse -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker Ho use -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker Hou se -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker Hous e -----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker House - ----" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker House -- ---" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker House --- --" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker House ---- -" )
  s.sleep(0.25)
  clearConsole()
  print("----- Welcome To Louis' Poker House ----- " )


printPokerHouse()